### ISSUE TITLE
code missing

### ISSUE THREAD

**Issue by BlackOrangeCat** [RadioActiveX1/Simple-IPv6-vlan#1]
Hi, this project is missing code, could you upload the missing code?

**Comment by SiddBhatt9600** [comment]
Hi, thanks for your comment. Actually I mostly intend to keep these source codes for my personal reference for other projects rather than a standalone working code.

If you want to create a simple ipv6 vlan, I shall upload a standalone working code too. Thanks again!!

**Comment by BlackOrangeCat** [comment]
It would be great if you could upload the code to create the vlan.

**Comment by SiddBhatt9600** [comment]
Hi, I have updated the code, please take a look and feel free to ask if you got any queries. I would request you to double the libraries being included, if they are installed on your environment or not.
